### ISSUE TITLE
Always requires "name" field filled in

### ISSUE THREAD

**Issue by mk-mxp** [oliverklee/ext-onetimeaccount#105]
Probably introduced by #89 

Without changing anything else but updating onetimeaccount to V3.0.2 the field 'name' is seen as required even if not shown.

**Comment by oliverklee** [comment]
@mk-mxp Thanks for the report. I'll look into it.

**Comment by mk-mxp** [comment]
BTW: We returned to 3.0.1 for now and everything is working fine.

**Comment by oliverklee** [comment]
@mk-mxp Thanks, I can reproduce the problem now.

**Comment by oliverklee** [comment]
I've just released version 3.0.3 with the fix for this problem:
https://github.com/oliverklee/ext-onetimeaccount/releases/tag/v3.0.3

**Comment by mk-mxp** [comment]
Thanks!
