### ISSUE TITLE
XLIFF file not found or well-formed?

### ISSUE THREAD

**Issue by mk-mxp** [oliverklee/ext-onetimeaccount#158]
I am setting up a Typo3 V9.5.19 (latest version of V9 series) test site, based on the Typo3 Introduction package. I am using onetimeaccount and seminars, and face this strange and totally unexpected problem when inserting the plugin into a page:

```
An error occurred trying to process items for field "FE user fields in the form:" (The path provided does not point to existing and accessible well-formed XML file. Reason: in EXT:onetimeaccount/Resources/Private/Language/locallang_db.xlf, line ).
```

In fact, the file does exist and is well-formed. I don't see anything problems in it, file rights are set as required.

Do you know anything else to check for?

![Screenshot_2020-06-12](https://user-images.githubusercontent.com/55182845/84482987-f6922200-ac98-11ea-922c-a62215330651.png)

**Comment by oliverklee** [comment]
You could check whether the key exists.

Maybe deleting the language caches could also help.

**Comment by mk-mxp** [comment]
In `Classes/BackEnd/FlexForms.php`, line 202 ff., the path is no longer solved correctly.

```php
        $languageFilePath = GeneralUtility::getFileAbsFileName('EXT:onetimeaccount/Resources/Private/Language/locallang_db.xlf');
```

does the trick.

**Comment by oliverklee** [comment]
Awesome! Would you be willing to create a pull request for this?

**Comment by mk-mxp** [comment]
I'm sorry I don't have time to do the PR for you. And it's not the root cause. `XliffParser::getParsedData()` should do that. In fact, I do not understand, why it does not. There is code for doing so, but it does not come out with the resolved filename but the unresolved input...

**Comment by mk-mxp** [comment]
There it is...languageKey is 'default', which does totally skip path resolving in `XliffParser::getParsedData()`. Would you be willing to file bug in Typo3 for that? I don't have an account there...
